#!/usr/bin/env python3
"""
Synthesizer: generates a synthesis report from recent articles and emails it.
Run every 2 days at 09:00 via cron.
"""
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

from config import Settings
from email_utils import send_email, send_failure_email

CONFIG_PATH = Path(__file__).parent / "config.yaml"
ENV_PATH = Path(__file__).parent / ".env"
DRY_RUN = "--dry-run" in sys.argv


def load_recent_articles(output_dir: Path, since_date: str) -> list[dict]:
    articles = []
    for topic_dir in output_dir.iterdir():
        if not topic_dir.is_dir() or topic_dir.name == "synthesis":
            continue
        for md_file in topic_dir.glob("*.md"):
            file_date = md_file.name[:10]
            if file_date >= since_date:
                text = md_file.read_text(encoding="utf-8")
                title = text.split("\n")[0].lstrip("# ").strip()
                articles.append({
                    "title": title,
                    "topic": topic_dir.name,
                    "date": file_date,
                    "content": text[:1500],
                    "path": str(md_file),
                })
    return articles


def format_synthesis_email(report_text: str, article_count: int, date_str: str) -> str:
    html_body = report_text.replace("\n", "<br>")
    html_body = re.sub(r"## (.+?)(<br>|$)", r"<h3>\1</h3>", html_body)
    html_body = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html_body)
    return f"""
<html><body style="font-family: sans-serif; max-width: 700px; margin: auto; padding: 20px;">
<h2>Info Digest -- {date_str}</h2>
<p style="color: #666;">{article_count} articles synthesized</p>
<hr>
{html_body}
<hr>
<p style="color: #999; font-size: 12px;">Generated by info-scraper</p>
</body></html>
"""


def synthesize_with_claude(articles: list[dict], preferences_text: str) -> str:
    articles_text = "\n\n".join(
        f"[{a['topic']}] {a['title']}\n{a['content'][:600]}"
        for a in articles
    )
    prompt = f"""You are a knowledge synthesizer helping a reader extract compound insights from recent articles.

User preferences:
{preferences_text}

Recent articles ({len(articles)} total):
{articles_text}

Generate a synthesis report with these sections:
## Key Themes
(3-5 recurring themes across articles)

## Notable Insights
(5-7 specific, concrete insights worth remembering)

## Actionable Items
(2-4 things the reader could DO right now based on what they read -- be specific)

## Emerging Signals
(1-3 early trends worth watching)

Be specific. Quote titles. No generic takes."""

    try:
        result = subprocess.run(
            ["claude", "-p", prompt],
            capture_output=True,
            text=True,
            timeout=180,
        )
        return result.stdout.strip()
    except Exception as e:
        raise RuntimeError(f"Claude CLI failed: {e}")


def get_since_date(days_back: int) -> str:
    since = datetime.now(timezone.utc) - timedelta(days=days_back)
    return since.strftime("%Y-%m-%d")


def main() -> None:
    settings = Settings.load(CONFIG_PATH, ENV_PATH)
    days_back = settings.config["schedule"]["synthesize_every_days"]
    since_date = get_since_date(days_back)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    output_dir = settings.output_dir
    preferences_text = (Path(__file__).parent / settings.preferences_path).read_text()

    print(f"[synthesizer] Loading articles since {since_date}...")
    articles = load_recent_articles(output_dir, since_date)

    if not articles:
        print("[synthesizer] No new articles since last synthesis. Skipping.")
        return

    print(f"[synthesizer] Synthesizing {len(articles)} articles with Claude...")
    try:
        report = synthesize_with_claude(articles, preferences_text)
    except RuntimeError as e:
        print(f"[synthesizer] ERROR: {e}", file=sys.stderr)
        send_failure_email("synthesizer", str(e), settings)
        return

    synthesis_dir = output_dir / "synthesis"
    synthesis_dir.mkdir(exist_ok=True)
    report_path = synthesis_dir / f"{today}-synthesis.md"
    report_path.write_text(f"# Synthesis Report -- {today}\n\n{report}", encoding="utf-8")
    print(f"[synthesizer] Report saved to {report_path}")

    if DRY_RUN:
        print("[dry-run] Would send email. Report preview:")
        print(report[:500])
        return

    html = format_synthesis_email(report, len(articles), today)
    try:
        send_email(f"Info Digest -- {today}", html, settings)
        print(f"[synthesizer] Email sent to {settings.config['email']['to']}")
    except Exception as e:
        error_msg = f"Email send failed: {e}\nReport saved at {report_path}"
        print(f"[synthesizer] ERROR: {error_msg}", file=sys.stderr)
        send_failure_email("synthesizer/email", error_msg, settings)


if __name__ == "__main__":
    main()
